services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/data
      - PORT=8080
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports: 
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
