// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package shared

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/muhhae/lorem-ipsum/pkg/component"

func NavBar() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex-1\"><a class=\"btn btn-ghost text-primary font-black text-xl sm:text-3xl\">Lorem Ipsum</a></div><div x-data=\"{\n                loggedIn : false,\n            }\" class=\"flex-none flex space-x-1 md:space-x-4\" hx-get=\"/api/v1/user/myName\" hx-target=\"#where-the-username-is\" hx-swap=\"innerHTML\" hx-trigger=\"load\" x-on:htmx:after-swap=\"loggedIn = true; $refs.loginbtn.remove()\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = component.ThemeSwitch().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a x-ref=\"loginbtn\" href=\"/login\" class=\"btn md:btn-md btn-sm text-lg md:text-2xl font-bold btn-ghost rounded-btn\">Sign In</a><div x-show=\"loggedIn\" class=\"h-full dropdown dropdown-end\"><div><button id=\"where-the-username-is\" class=\"btn md:btn-md btn-sm text-lg md:text-2xl font-bold btn-ghost rounded-btn\">username</button></div><ul tabindex=\"0\" class=\"rounded-xl menu menu-sm dropdown-content mt-3 z-[1] \n                        p-2 shadow bg-base-300 w-52\"><li><a hx-get=\"/api/v1/user/logout\" hx-swap=\"none\">Logout</a></li></ul></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = component.Navbar().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
